garryarts/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace="rest_framework")),
    path('api-token-auth/', views.obtain_auth_token),
    path('',include('home.urls')),
    path('telegram/',include('telegram.urls',namespace="telegram"))
]

home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import SimpleRouter
from django.views.decorators.csrf import csrf_exempt
from . import views
from . import apiviews

app_name="home"
urlpatterns = [
    path('',views.HomeView.as_view(),name="home"),
    path('place-art-order/',views.PlaceOrderView.as_view(),name="place-art-order"),
    path('version/',views.GetVersion.as_view(),name="version"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
class Art(models.Model):
    image=models.ImageField(upload_to="arts")
    caption=models.CharField(max_length=255)
    price=models.FloatField(default=0.0)
    available=models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return f"{self.image.name} - {self.caption}"

class Customer(models.Model):
    phone=models.CharField(max_length=20,unique=True)
    name=models.CharField(max_length=200,default="Anonymous")
    
    def __str__(self) -> str:
        return f"{self.phone}|{self.name}"

class ArtOrder(models.Model):
    arts=models.ManyToManyField(Art,related_name="art_orders")
    customer=models.ForeignKey(Customer,related_name="art_orders",on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now=True)

home/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from . import models
from .serializers import (
    ArtSerializer,
    ArtOrderSerializer
)
from rest_framework.views import APIView
from rest_framework import authentication
from rest_framework import permissions
from rest_framework.response import Response
from django.conf import settings
from telegram.functions import send_notification

# Create your views here.
class GetVersion(APIView):
    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = [permissions.AllowAny]
    def get(self,request):
        return Response({'version':settings.VERSION})
    
class HomeView(ListView):
    model=models.Art
    context_object_name="arts"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["arts"] = ArtSerializer(context["arts"],many=True).data
        return context

class PlaceOrderView(TemplateView):
    template_name="home/placeOrder.html"
    
    def post(self,request):
        data = dict(request.POST)
        info = {
            "phone":request.POST["phone"],
            "name":request.POST["name"],
            "arts":[x for x in data["arts"]]
        }
        
        customer,createdCustomer = models.Customer.objects.get_or_create(phone=info["phone"],defaults={"name":info["name"]})
        if not createdCustomer:
            customer.name = info["name"]
            customer.save()
        artorder = models.ArtOrder.objects.create(customer=customer)
        artorder.save()
        for art in info["arts"]:
            artorder.arts.add(art)
        
        send_notification(f"{customer.name}, phone: {customer.phone}.\n Placed an order.")

        return render(request,self.template_name,{"artOrder":artorder})
    

home/templates/home/art_list.html
{% extends 'base.html' %}
{% block title %} - Arts{% endblock title %}

{% block navbarCollapse %}
<button type="button" class="btn btn-primary d-flex" data-bs-toggle="modal" data-bs-target="#cartModal">Cart <span class="badge text-bg-warning mx-1" id="cart-size">0</span></button>
{% endblock navbarCollapse %}

{% block main %}
<div class="container-sm">
    <div class="arts">
    {% for art in arts %}
    <div class="card text-bg-dark mx-1 shadow border-primary">
        <img src="{{art.image}}" class="card-img" alt="{{art.caption}}">
        <div class="card-img-overlay bg-dark p-2 bg-opacity-50">
            <h5 class="card-title">K{{art.price}}</h5>
          <p class="card-text">{{art.caption}}</p>
        </div>
        <div class="card-footer">
            <div class="btn-group w-100" role="group" aria-label="Basic outlined example" data-art-id="{{art.id}}" data-art-image="{{art.image}}">
              {% if art.available %}
              <button type="button" class="btn btn-success add-to-cart" data-art-available="{{art.available}}">Add to Cart</button>
              {% else %}
              <button type="button" class="btn btn-danger" disabled>Sold</button>
              {% endif %}
              <button type="button" class="btn btn-primary view-image" data-art-available="{{art.available}}" data-bs-toggle="modal" data-bs-target="#imageViewer">View image</button>
            </div>
        </div>
      </div>
    {% endfor %}
    </div>
    <!-- Button trigger modal -->
  
  <!-- Modal -->
  <div class="modal fade" id="imageViewer" tabindex="-1" aria-labelledby="imageViewerLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="imageViewerLabel">Image Viewer</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <img src="" class="img-fluid" alt="..." />
        </div>
        <div class="modal-footer">
            <div class="btn-group w-100" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-success img-add-to-cart">Add to Cart</button>
              <button type="button" class="btn btn-warning place-order" data-bs-toggle="modal" data-bs-target="#cartModal">Place Order</button>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <!-- Modal -->
  <div class="modal fade" id="cartModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="cartModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="cartModalLabel">Cart</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="orderForm" method="POST" action="{% url 'home:place-art-order' %}">
            {% csrf_token %}
            <div id="orderContainer" class="row row-cols-1 row-cols-md-3 g-4"></div>
            <div class="form-floating mb-3">
              <input type="tel" class="form-control" name="phone" placeholder="(+260) --- ------" required>
              <label for="phone">Phone number</label>
            </div>
            <div class="form-floating mb-3">
              <input type="text" class="form-control" name="name" placeholder="John Doe" required>
              <label for="name">Name</label>
            </div>
            <button id="submitOrder" type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>

{{arts|json_script:"arts-json"}}
{% endblock main %}

{% block jstags %}
<script>
    var cart = []
    $(document).ready(()=>{
        $(".arts").slick({
            accessibility:true,
            arrows:true,
            lazyLoad:"ondemand",
            slidesToShow:3,
            slidesToScroll:1,
            dots:true,
            centerMode:true,
            centerPadding: '20px',
            adaptiveHeight: true,
            responsive:[
            {
                breakpoint:1024,
                settings:{
                    slidesToShow:3,
                    slidesToScroll:1
                }
            },
            {
                breakpoint:600,
                settings:{
                    slidesToShow:2,
                    slidesToScroll:1
                }
            },
            {
                breakpoint:480,
                settings:{
                    slidesToShow:1,
                    slidesToScroll:1
                }
            }
            ]
        });

        var arts_json = document.querySelector("#arts-json").innerText
        
        document.querySelectorAll(".view-image").forEach((item)=>{
            item.addEventListener("click",(event)=>{
              var img = document.querySelector("#imageViewer img")
              img.setAttribute("src",event.target.parentElement.getAttribute("data-art-image"))
              img.setAttribute("data-art-id",event.target.parentElement.getAttribute("data-art-id"))
              if(event.target.getAttribute("data-art-available")=="True"){
                document.querySelector("#imageViewer .img-add-to-cart").innerText = "Add To Cart"
              } else {
                document.querySelector("#imageViewer .img-add-to-cart").innerText = "Sold"
                document.querySelector("#imageViewer .img-add-to-cart").setAttribute("disabled","true")
                document.querySelector("#imageViewer .place-order").setAttribute("disabled","true")
              }
            })
        })
        document.querySelectorAll(".add-to-cart").forEach((item)=>{
            item.addEventListener("click",(event)=>{
                cart.push({
                    id:event.target.parentElement.getAttribute("data-art-id"),
                    image:event.target.parentElement.getAttribute("data-art-image")
                })
                renderCart()
            })
        })
        document.querySelectorAll(".img-add-to-cart").forEach((item)=>{
            item.addEventListener("click",(event)=>{
              var img = document.querySelector("#imageViewer img")
                cart.push({
                    id:img.getAttribute("data-art-id"),
                    image:img.getAttribute("src")
                })
                renderCart()
            })
        })
        document.querySelectorAll(".place-order").forEach((item)=>{
            item.addEventListener("click",(event)=>{
              cart = []
              var img = document.querySelector("#imageViewer img")
                cart.push({
                    id:img.getAttribute("data-art-id"),
                    image:img.getAttribute("src")
                })
                renderCart()
            })
        })
        document.querySelector("#orderForm").addEventListener("submit",(event)=>{
          if (cart.length === 0) {
            event.preventDefault()
            alert("Cart is empty!")
          }
        })
    });
    function removeDuplicates(arr) {
      var unique = []
      arr.forEach((item)=>{
        unique = unique.filter((it)=>{
          return it.id !== item.id
        })
        unique.push(item)
      })
      return unique
    }

    function renderCart(){
        var orderForm = document.querySelector("#orderForm")
        var container = document.querySelector("#orderContainer")
        container.innerHtml = ""
        container.innerText = ""
        cart = removeDuplicates(cart);
        cart.forEach((item,index,arr)=>{
            var col = document.createElement("div")
            col.classList.add("col","mb-3")
            container.appendChild(col)

            var card = document.createElement("div")
            card.classList.add("card")
            col.appendChild(card)

            var img = document.createElement("img")
            img.classList.add("card-img-top")
            img.setAttribute("src",item.image)
            card.appendChild(img)

            var cardBody = document.createElement("div")
            cardBody.classList.add("card-body")
            card.appendChild(cardBody)

            var input = document.createElement("input")
            input.setAttribute("type","text")
            input.setAttribute("name","arts")
            input.setAttribute("readonly","true")
            input.setAttribute("hidden","true")
            input.setAttribute("value",item.id)
            input.setAttribute("data-cart-index",index)
            input.classList.add("form-control")
            cardBody.appendChild(input)

            var cardFooter = document.createElement("div")
            cardFooter.classList.add("card-footer")
            card.appendChild(cardFooter)

            var removeButton = document.createElement("button")
            removeButton.classList.add("btn","btn-danger","remove-button")
            removeButton.setAttribute("data-cart-index",index)
            removeButton.innerText = "Remove"
            removeButton.addEventListener("click",(event)=>{
              event.preventDefault()
              var index = event.target.getAttribute("data-cart-index")
              cart = cart.filter((it)=>{
                return it !== item
              })
              renderCart()
            })
            cardFooter.appendChild(removeButton)
        })
        document.querySelector("#cart-size").innerText = cart.length
    }
</script>
{% endblock jstags %}

home/templates/home/placeOrder.html
{% extends 'base.html' %}
{% block title %} - Order {{artOrder.id}}{% endblock title %}

{% block main %}
<div class="container-sm my-3">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Well Done! {{artOrder.customer.name}}</h4>
        <p>You will be contacted through the number you have provided <b>{{artOrder.customer.phone}}</b></p>
        <p>If you dont get a call in less that 2 hours, consider it being a communication issue with us. Most orders are attended to minutes just after being placed.</p>
        <hr>
        <p class="mb-0">Your art order has successfully been submitted.</p>
      </div>
</div>
{% endblock main %}